# Generated by Django 5.1.5 on 2025-04-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examquestion',
            name='marks',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='question_attachment',
            field=models.FileField(blank=True, null=True, upload_to='exam_question_attachments/'),
        ),
    ]
