# Generated by Django 5.1.5 on 2025-04-09 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_userpreference_accent_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreference',
            name='accent_color',
        ),
    ]
