# Generated by Django 5.1.5 on 2025-04-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_remove_userpreference_accent_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='font_style',
            field=models.CharField(choices=[('sans-serif', 'Sans Serif'), ('serif', 'Serif'), ('monospace', 'Monospace'), ('inter', 'Inter'), ('poppins', 'Poppins'), ('roboto', 'Roboto')], default='sans-serif', max_length=20),
        ),
    ]
