# Generated by Django 5.1.5 on 2025-04-20 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_attachment',
            field=models.FileField(blank=True, null=True, upload_to='question_attachments/'),
        ),
    ]
