# Generated by Django 5.1.5 on 2025-03-14 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_chatmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
